//index.js
//获取应用实例
const app = getApp();

Page({
    data: {
        name:'我的',
        person: {
            headerImg:'',
            balance:'',
            grandTotal:''
        },
        projectList:[{
            name:'我的能力',
            left_img:'../../image/image.jpg',
            right_img:'../../image/back.png'
        },{
            name:'我的问题',
            left_img:'../../image/image.jpg',
            right_img:'../../image/back.png'
        },{
            name:'我的订单',
            left_img:'../../image/image.jpg',
            right_img:'../../image/back.png'
        },{
            name:'我的评论',
            left_img:'../../image/image.jpg',
            right_img:'../../image/back.png'
        },{
            name:'帮助中心',
            left_img:'../../image/image.jpg',
            right_img:'../../image/back.png'
        },{
            name:'关于我们',
            left_img:'../../image/image.jpg',
            right_img:'../../image/back.png'
        },],
    },
    onLoad(){
        console.log('onLoad');
        this.setData({
            'person.name':'暗月',
            'person.headerImg':'../../image/image2.jpg',
            'person.balance':'25.00',
            'person.grandTotal':'1323.73',
        },function () {
            console.log('callback')
        });
        wx.setNavigationBarTitle({
            title:this.data.name
        })
    },
    onShow(){
        console.log('onShow')
    },
    onReady(){
        console.log('onReady')
    },
    onHide(){
        console.log('onHide')
    }
});
