Page({
    data:{
        question_detail:{
            title:'',
            info:'',
            header_name:'',
            header_img:'',
            time:'',
            imgList:['../../image/image.jpg','../../image/image2.jpg','../../image/image3.jpg']
        }
    },
    onLoad(){
        this.setData({
            'question_detail.title':'北京自动化',
            'question_detail.info':'222222',
            'question_detail.header_name':'暗*月',
            'question_detail.header_img':'../../image/image.jpg',
            'question_detail.time':'2019年5月7日',
        })
    }
});